### PR TITLE
Add SavePlotLogs setting

### PR DESCRIPTION
**Pull request by djatwood**
In reference to #17 and #32 

I have added a `SavePlotLogs` setting that writes to `~/.chia/mainnet/plotter/plotng_log_ID.txt`. This should be cross platform as it uses os specific separators when creating the file.

### CODE REVIEW

**Comment by maded2** [comment]
Thanks for the PR.  

I do have a suggestion, if we have config "SavePlotLogDir" in the json file.  If the user put a valid directory path there then the log files is created there.  The default should be empty string which means no log files is created.

**Comment by djatwood** [comment]
Just for clarification, do you mean replace `SavePlotLogs` with `SavePlotLogDir`?

**Comment by maded2** [comment]
Yes, I do.  I think it is the simplest and most flexible solution.

**Comment by djatwood** [comment]
Should be all set. I'm going to test overnight and will report in the morning.

**Pull request merged**
